version: '3.7'

services:
  web:
    build: enigma_test_app
    command: gunicorn apps.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    expose:
      - 8000
    env_file:
      - enigma_test_app/.env
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - enigma_test_app/.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: