# Generated by Django 4.2.4 on 2023-08-23 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('self', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.characteristic')),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('characteristic', models.ManyToManyField(to='Catalog.characteristic')),
            ],
        ),
        migrations.CreateModel(
            name='FilialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.product')),
            ],
        ),
    ]
