# Generated by Django 4.2.4 on 2023-08-23 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('self', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.characteristic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('region', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('characteristic', models.ManyToManyField(to='catalog.characteristic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilialPrice',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
