# Generated by Django 4.2.4 on 2023-08-28 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='self',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.characteristic'),
        ),
        migrations.AlterField(
            model_name='filialprice',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.filial'),
        ),
        migrations.AlterField(
            model_name='filialprice',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=models.ManyToManyField(null=True, to='catalog.characteristic'),
        ),
    ]
